---
name: Rerun workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 0-14 21 4 *'

jobs:
  rerun_by_id:
    name: Rerun by workflow id
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.WORKFLOW_TOKEN }}" \
            "https://api.github.com/repos/MediaMarktSaturn/sterling-messaging-adapter/actions/runs/2198177138/rerun"
