---
name: Run on dev path
on:
  push:
    branches:
      - 'master'
    paths:
      - "env/dev/hello.sh"

jobs:
  dev:
    name: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./env/dev/hello.sh 'run workflow on dev change'
